version: '3.5'

services:
  postgres:
    container_name: postgres_main_db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: recruitment_job
    ports:
    - "5432:5432"
